DROP DATABASE frisoer;
CREATE DATABASE frisoer;
USE frisoer;
CREATE TABLE user (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(45));
CREATE TABLE termin (id INT PRIMARY KEY AUTO_INCREMENT, slot DATETIME NOT NULL, user_id INT NOT NULL);
INSERT INTO user (id, name) VALUES(NULL, 'Gabor');
INSERT INTO user (id, name) VALUES(NULL, 'Dominik');
INSERT INTO user (id, name) VALUES(NULL, 'Tung');
INSERT INTO user (id, name) VALUES(NULL, 'Mate');
INSERT INTO user (id, name) VALUES(NULL, 'Daniel');
INSERT INTO user (id, name) VALUES(NULL, 'Rolf');
INSERT INTO user (id, name) VALUES(NULL, 'Michael');
INSERT INTO termin (id, slot, user_id) VALUES(NULL, '2023-01-31 11:00:00', 1);
INSERT INTO termin (id, slot, user_id) VALUES(NULL, '2023-02-01 10:00:00', 2);
INSERT INTO termin (id, slot, user_id) VALUES(NULL, '2023-02-02 12:00:00', 3);
INSERT INTO termin (id, slot, user_id) VALUES(NULL, '2023-02-03 12:00:00', 4);
INSERT INTO termin (id, slot, user_id) VALUES(NULL, '2023-02-03 14:00:00', 5);
INSERT INTO termin (id, slot, user_id) VALUES(NULL, '2023-02-04 12:00:00', 6);
INSERT INTO termin (id, slot, user_id) VALUES(NULL, '2023-02-04 13:00:00', 7);
ALTER TABLE termin ADD CONSTRAINT FOREIGN KEY (user_id) REFERENCES user (id);
SHOW TABLES;
DESCRIBE termin;
DESCRIBE user;
SELECT * FROM termin;
SELECT * FROM user;
